# Generated by Django 2.1.4 on 2018-12-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=50)),
                ('Applicant_exp', models.CharField(max_length=2)),
                ('Applicant_cv', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
