# Generated by Django 2.1.4 on 2018-12-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_app', '0002_auto_20181221_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantcv',
            old_name='Applicant_cv',
            new_name='applicant_cv',
        ),
        migrations.RenameField(
            model_name='applicantcv',
            old_name='Applicant_exp',
            new_name='applicant_exp',
        ),
        migrations.AddField(
            model_name='applicantcv',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
