# Generated by Django 2.1.4 on 2018-12-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan_app', '0006_cvkeywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantcv',
            name='applicant_exp',
        ),
    ]
