# Generated by Django 2.1.4 on 2018-12-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_app', '0007_remove_applicantcv_applicant_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neg_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_value', models.CharField(max_length=50)),
            ],
        ),
    ]
