# Generated by Django 2.1.4 on 2019-01-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_app', '0008_neg_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCollege_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=100)),
                ('clg_rank', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantDegree_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('degree_rank', models.CharField(max_length=3)),
            ],
        ),
    ]
