# Generated by Django 2.1.4 on 2019-01-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_app', '0010_auto_20190101_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantcv',
            name='cv_ext',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
