# Generated by Django 3.0.8 on 2020-07-12 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan_app', '0011_applicantcv_cv_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantcv',
            name='approved_by_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantcv',
            name='approved_by_mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantcv',
            name='approved_by_tr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tr', to=settings.AUTH_USER_MODEL),
        ),
    ]
