# Generated by Django 2.2.14 on 2020-07-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan_app', '0012_auto_20200712_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantcv',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cvs_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantcv',
            name='approved_by_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cvs_by_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantcv',
            name='approved_by_mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cvs_by_mr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantcv',
            name='approved_by_tr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cvs_by_tr', to=settings.AUTH_USER_MODEL),
        ),
    ]
